[SDPA-3132] Added config override inspector module.
dpc-sdp/baywatch pull request #53
Opened 2022-04-11 23:44 UTC by nicksantamaria

2022-04-11 23:53 UTC, MdNadimHossain commented
Nice one @nicksantamaria. Can you please also add it to the install function [here](https://github.com/dpc-sdp/baywatch/blob/59faafc89c5098239a1979cc7d97452ebaf8634b/baywatch.install#L16) so it gets installed for the new projects.

2022-04-11 23:54 UTC, MdNadimHossain requested changes
One small change needed, see the comment :)

2022-04-11 23:58 UTC, MdNadimHossain approved these changes

2022-04-13 03:20 UTC, nicksantamaria commented
I tested this on the reference site and it works well
![Screenshot 2022-04-13 at 1 09 17 pm](https://user-images.githubusercontent.com/121107/163093506-66d722a9-d085-448b-bead-7060bd5159c0.png)
.

2022-04-13 03:20 UTC, merged