[SDPAP-6973]hook update to delete page content type and existing nodes
dpc-sdp/baywatch pull request #74
Opened 2022-11-25 08:01 UTC by yeniatencio

2024-01-21 22:33 UTC, nicksantamaria commented on baywatch.install
> + * remove any existing nodes of type page content type
I'm not at all across what this PR is about, but deleting every page node across all tide projects seems quite risky.

2024-01-21 22:48 UTC, krakerag commented
@yeniatencio I can't see on the ticket any mention of deleting this page content type from _all_ cms being confirmed - only from royalcommission.

I can't pass this without someone taking responsibility for the decision of deleting content of this type across all CMS rather than just the royalcommission cms like the ticket says.

Let me know please :)

2024-01-21 22:49 UTC, krakerag requested changes
Can we find out if this is meant to be deleted from all CMS or just the royalcommission CMS please

2024-01-21 23:04 UTC, yeniatencio commented
> Can we find out if this is meant to be deleted from all CMS or just the royalcommission CMS please

Hi @nicksantamaria @krakerag , I am following solution direction of this [ticket](https://digital-vic.atlassian.net/browse/SDPAP-7015) and it mentions to create a hook update in baywatch module to remove any existing node of the page content type and remove permanently page content type. 
Here is the screenshot of the subtasks tickets. 
![Screenshot 2024-01-22 at 9 53 13 am](https://github.com/dpc-sdp/baywatch/assets/47239456/461b7111-3ed8-4bc5-9dad-bc34e21e314d)
 
I am going to confirm with Vanessa if remove page content type from all cms is what we are aiming for.

2024-01-22 02:42 UTC, yeniatencio commented
Vanessa and Sarah confirmed that Health is still using page so it shouldn't be removed in core. Closing this ticket.

2024-01-22 02:42 UTC, closed without merging