Update section purger plugin to sectionbundled
dpc-sdp/baywatch pull request #84
Opened 2023-06-01 22:36 UTC by MarkCalvert

2023-06-04 22:10 UTC, steveworley requested changes
Great! Update hook looks good, I think we will also need to update config/install so when a new site installs baywatch they will have the bundled purger configured directly.

2023-06-07 06:53 UTC, steveworley approved these changes

2023-06-07 06:56 UTC, steveworley commented
Hey @GROwen would you mind having a review of this proposed change? There is a [bundled purger](https://git.drupalcode.org/project/section_purge/-/blob/master/src/Plugin/Purge/Purger/SectionBundledPurger.php) plugin in the Section module which provides the ability to invalidate multiple tags in one request.

This is an update hook to update the section purger configuration values for deployed sites (as they're not all using the config provided by Baywatch).

2023-06-07 07:00 UTC, GROwen commented on baywatch.install
> +        $channel['id'] = "purger_sectionbundled_$purger_id";
Should this be 
```suggestion
        $channel['id'] = "purger_sectionbundled_{$purger_id}";
```

2023-06-07 07:02 UTC, GROwen commented
Hey @steveworley and @MarkCalvert Is the sectionbundled purger an existing purger or do we need to bump the version of the module?

Also, this belongs in https://github.com/dpc-sdp/bay_platform_dependencies/ We moved platform dependencies there a little while ago.

2023-06-07 07:05 UTC, steveworley commented
Thanks @GROwen — sorry I forgot that platform deps were split out. Nope, the section module was bundled with this for a while — unsure why we didn't use this in the initial set up of the module.

Will get it moved to the right place, thanks!

2023-06-07 07:05 UTC, closed without merging

2023-06-08 00:31 UTC, MarkCalvert commented
Migrated PR to https://github.com/dpc-sdp/bay_platform_dependencies/pull/2